  name: CI - Lint and Build Next.js

  on:
    push:
      branches:
        - dev

    pull_request:
      branches:
        - '*' 

    workflow_dispatch:

  jobs:
    ci:
      if: |
        github.event_name == 'push' ||
        (
          github.event_name == 'pull_request' &&
          (
            startsWith(github.head_ref, 'feature/') ||
            startsWith(github.head_ref, 'bugfix/') ||
            startsWith(github.head_ref, 'hotfix/')
          )
        )
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Detect package manager
          id: detect-package-manager
          run: |
            if [ -f "yarn.lock" ]; then
              echo "manager=yarn" >> $GITHUB_OUTPUT
              echo "command=install" >> $GITHUB_OUTPUT
              echo "runner=yarn" >> $GITHUB_OUTPUT
            else
              echo "manager=npm" >> $GITHUB_OUTPUT
              echo "command=ci" >> $GITHUB_OUTPUT
              echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            fi

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20"
            cache: ${{ steps.detect-package-manager.outputs.manager }}

        - name: Create .env file from GitHub Secrets
          run: |
            echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
            echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
            echo "GA4_MEASUREMENT_ID=${{ secrets.GA4_MEASUREMENT_ID }}" >> .env.local
            echo "GA4_API_SECRET=${{ secrets.GA4_API_SECRET }}" >> .env.local

        - name: Install dependencies
          run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

        - name: Run Lint
          run: ${{ steps.detect-package-manager.outputs.runner }} next lint

        - name: Build project
          run: ${{ steps.detect-package-manager.outputs.runner }} next build
