name: Build and Deploy Docker Image to Remote Server -1

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        - name: Create .env file from GitHub Secrets
          run: |
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.local
            echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.local
            echo "GA4_MEASUREMENT_ID=${{ secrets.GA4_MEASUREMENT_ID }}" >> .env.local
            echo "GA4_API_SECRET=${{ secrets.GA4_API_SECRET }}" >> .env.local 
            echo "STREAMABLE_USERNAME=${{ secrets.STREAMABLE_USERNAME }}" >> .env.local 
            echo "STREAMABLE_PASSWORD=${{ secrets.STREAMABLE_PASSWORD }}" >> .env.local 
            echo "MSG91_AUTH_KEY=${{ secrets.MSG91_AUTH_KEY }}" >> .env.local 
            echo "MSG91_WIDGET_ID=${{ secrets.MSG91_WIDGET_ID }}" >> .env.local 
            echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env.local 
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local 

        - name: Confirm .env.local contents (safe for public values only)
          run: cat .env.local


        - name: Install dependencies
          run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

        - name: Run Lint
          run: ${{ steps.detect-package-manager.outputs.runner }} next lint

        - name: Build project
          run: ${{ steps.detect-package-manager.outputs.runner }} next build